//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartH2O_DLog.ServiceLog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLog.IServiceLog")]
    public interface IServiceLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLog/DoWork", ReplyAction="http://tempuri.org/IServiceLog/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLog/DoWork", ReplyAction="http://tempuri.org/IServiceLog/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLog/SendValues", ReplyAction="http://tempuri.org/IServiceLog/SendValuesResponse")]
        string SendValues(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLog/SendValues", ReplyAction="http://tempuri.org/IServiceLog/SendValuesResponse")]
        System.Threading.Tasks.Task<string> SendValuesAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLog/GetAllValues", ReplyAction="http://tempuri.org/IServiceLog/GetAllValuesResponse")]
        string GetAllValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLog/GetAllValues", ReplyAction="http://tempuri.org/IServiceLog/GetAllValuesResponse")]
        System.Threading.Tasks.Task<string> GetAllValuesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLogChannel : SmartH2O_DLog.ServiceLog.IServiceLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLogClient : System.ServiceModel.ClientBase<SmartH2O_DLog.ServiceLog.IServiceLog>, SmartH2O_DLog.ServiceLog.IServiceLog {
        
        public ServiceLogClient() {
        }
        
        public ServiceLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string SendValues(string data) {
            return base.Channel.SendValues(data);
        }
        
        public System.Threading.Tasks.Task<string> SendValuesAsync(string data) {
            return base.Channel.SendValuesAsync(data);
        }
        
        public string GetAllValues() {
            return base.Channel.GetAllValues();
        }
        
        public System.Threading.Tasks.Task<string> GetAllValuesAsync() {
            return base.Channel.GetAllValuesAsync();
        }
    }
}
